spring.application.name=Advertisement
server.port=10000
server.address=0.0.0.0
spring.application.name=Advertisement
server.port=10000
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ezjekakvqdwprsrtczrh
spring.datasource.password=Yj$!jC+4sYFjNX&

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

